<a href="https://colab.research.google.com/github/possomartin/Notebooks/blob/main/Demo_Pipeline_GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries import

In [ ]:
# Standard Libraries
import random as rn
import pandas as pd
import numpy as np

# Datasets
from sklearn import datasets

# Split test Train Data
from sklearn.model_selection import train_test_split

# Create Pipeline
from sklearn.pipeline import Pipeline

# Grid Search to find best HyperParameter
from sklearn.model_selection import GridSearchCV

# StandarScaler
from sklearn.preprocessing import StandardScaler

# Models to be used
  # Classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Read Dataset

In [ ]:
wine = datasets.load_wine()

X = wine.data
y = wine.target

# Prepare Data for training

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42) # Split training data and test data

# Pipe Line

In [ ]:
seed = 142

clf = Pipeline([('scl', StandardScaler()), ('classifier', DecisionTreeClassifier(random_state=seed))]) # Pipeline to Scale Data and then Fit Model

classifier_param_grid = [
    {
      "classifier":[DecisionTreeClassifier(random_state=seed)], # Model
      "classifier__criterion":["gini","entropy"], # Parameters from Model
      "classifier__max_depth":np.arange(10, 21, 2),
     },
     {
      "classifier":[RandomForestClassifier(random_state=seed)],
      "classifier__criterion":["gini","entropy"],
      "classifier__n_estimators":np.arange(50, 1200, 500),
     }
]

# Grid Data Search CV

In [ ]:
clf_grid_search = GridSearchCV(estimator=clf, param_grid=classifier_param_grid, scoring='accuracy', cv=3, return_train_score=True) # Grid Search CV to tune with best Hyperparameters

# Model Fitting

In [ ]:
grids = [clf_grid_search] # you can create an array of grids and then loop each to train
grids[0].fit(X_train, y_train) # Model Fitting

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('scl', StandardScaler()),
                                       ('classifier',
                                        DecisionTreeClassifier(random_state=142))]),
             param_grid=[{'classifier': [DecisionTreeClassifier(random_state=142)],
                          'classifier__criterion': ['gini', 'entropy'],
                          'classifier__max_depth': array([10, 12, 14, 16, 18, 20])},
                         {'classifier': [RandomForestClassifier(n_estimators=550,
                                                                random_state=142)],
                          'classifier__criterion': ['gini', 'entropy'],
                          'classifier__n_estimators': array([  50,  550, 1050])}],
             return_train_score=True, scoring='accuracy')

In [ ]:
results_ = pd.DataFrame(clf_grid_search.cv_results_)
results_

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.002534      0.001227         0.001476        0.001484   
1        0.001637      0.000166         0.000374        0.000007   
2        0.001459      0.000006         0.000416        0.000007   
3        0.001474      0.000036         0.000524        0.000177   
4        0.001489      0.000065         0.000384        0.000017   
5        0.001478      0.000073         0.000369        0.000012   
6        0.001630      0.000023         0.000387        0.000011   
7        0.001760      0.000118         0.000401        0.000029   
8        0.001681      0.000045         0.000389        0.000011   
9        0.001674      0.000007         0.000380        0.000013   
10       0.001683      0.000021         0.000384        0.000003   
11       0.001694      0.000046         0.000398        0.000019   
12       0.068955      0.004737         0.005915        0.000559   
13       0.755221      0.085332         0.065268        0.020137   
14       1.308999      0.024997         0.148726        0.078264   
15       0.068302      0.004569         0.005158        0.000246   
16       0.701378      0.007312         0.049568        0.002522   
17       1.371511      0.011605         0.108637        0.015164   

                                     param_classifier  \
0            DecisionTreeClassifier(random_state=142)   
1            DecisionTreeClassifier(random_state=142)   
2            DecisionTreeClassifier(random_state=142)   
3            DecisionTreeClassifier(random_state=142)   
4            DecisionTreeClassifier(random_state=142)   
5            DecisionTreeClassifier(random_state=142)   
6            DecisionTreeClassifier(random_state=142)   
7            DecisionTreeClassifier(random_state=142)   
8            DecisionTreeClassifier(random_state=142)   
9            DecisionTreeClassifier(random_state=142)   
10           DecisionTreeClassifier(random_state=142)   
11           DecisionTreeClassifier(random_state=142)   
12  RandomForestClassifier(n_estimators=550, rando...   
13  RandomForestClassifier(n_estimators=550, rando...   
14  RandomForestClassifier(n_estimators=550, rando...   
15  RandomForestClassifier(n_estimators=550, rando...   
16  RandomForestClassifier(n_estimators=550, rando...   
17  RandomForestClassifier(n_estimators=550, rando...   

   param_classifier__criterion param_classifier__max_depth  \
0                         gini                          10   
1                         gini                          12   
2                         gini                          14   
3                         gini                          16   
4                         gini                          18   
5                         gini                          20   
6                      entropy                          10   
7                      entropy                          12   
8                      entropy                          14   
9                      entropy                          16   
10                     entropy                          18   
11                     entropy                          20   
12                        gini                         NaN   
13                        gini                         NaN   
14                        gini                         NaN   
15                     entropy                         NaN   
16                     entropy                         NaN   
17                     entropy                         NaN   

   param_classifier__n_estimators  \
0                             NaN   
1                             NaN   
2                             NaN   
3                             NaN   
4                             NaN   
5                             NaN   
6                             NaN   
7                             NaN   
8                             NaN   
9                             NaN   
10                            NaN   
11  

# Results

In [ ]:
grid_dict = {0: 'Classifiers'}
print('{} Test Accuracy: {}'.format(grid_dict[0], clf_grid_search.score(X_test, y_test))) # show score results with test data
print('{} Best Params: {}'.format(grid_dict[0], clf_grid_search.best_params_)) #list best parameters based on the Grid Params we gave to looked for

Classifiers Test Accuracy: 1.0
Classifiers Best Params: {'classifier': RandomForestClassifier(n_estimators=550, random_state=142), 'classifier__criterion': 'gini', 'classifier__n_estimators': 550}


## Test

In [ ]:
y_test

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 0, 1])

In [ ]:
clf_grid_search.predict(X_test)

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 0, 1])

In [ ]:
y_test == clf_grid_search.predict(X_test)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])